-- HDFC Bank Oracle Database Setup
-- Create Tablespaces for HDFC Bank Microservices

-- Connect as SYS or SYSTEM user
-- CREATE TABLESPACES FOR HDFC BANK

-- Data Tablespace
CREATE TABLESPACE HDFC_DATA
DATAFILE 'hdfc_data.dbf' SIZE 2G
AUTOEXTEND ON
NEXT 100M
MAXSIZE 10G
EXTENT MANAGEMENT LOCAL
AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

-- Index Tablespace
CREATE TABLESPACE HDFC_INDEX
DATAFILE 'hdfc_index.dbf' SIZE 1G
AUTOEXTEND ON
NEXT 50M
MAXSIZE 5G
EXTENT MANAGEMENT LOCAL
AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;

-- Temporary Tablespace
CREATE TEMPORARY TABLESPACE HDFC_TEMP
TEMPFILE 'hdfc_temp.dbf' SIZE 500M
AUTOEXTEND ON
NEXT 50M
MAXSIZE 2G
EXTENT MANAGEMENT LOCAL
UNIFORM SIZE 1M;

-- UNDO Tablespace
CREATE UNDO TABLESPACE HDFC_UNDO
DATAFILE 'hdfc_undo.dbf' SIZE 1G
AUTOEXTEND ON
NEXT 100M
MAXSIZE 3G
EXTENT MANAGEMENT LOCAL
AUTOALLOCATE;